# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Steven Walsh
tagline: Web Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Graduated (June 2017) from the Web Development Diploma program at College of the North Atlantic. 
I am a junior web developer with a strong desire to learn and grow with a professional company. 
I have a good foundation in object-oriented programming; website planning, design, development, and testing (desktop and mobile);
user-interface design; web frameworks; web server administration (Windows and Linux); computer networking; multimedia development;
and database design and development.'

#sidebar links
email: swalsh99@hotmail.com
phone: 709-769-3041
github: stevenjwalsh

#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
